### ISSUE TITLE
Issues regarding the DBSCAN hyperparameters finding.

### ISSUE THREAD

**Issue by miss77jun** [HWaymentSteele/AF_Cluster#1]
Hi, I am using AF_Cluster for predicting alternative conformations for some proteins.
However, the scan for epsilon fails for cases where the epsilon scan is stopped by the condition of esp>10 and n_clust==1. 

May I ask why this condition is mandatory during the DBSCANs?
What is the best way to work around the situation where for all eps <= 10 and n_clust==1 there only exists one cluster?

Referring to file [AF_Cluster](https://github.com/HWaymentSteele/AF_Cluster)/[scripts](https://github.com/HWaymentSteele/AF_Cluster/tree/main/scripts)/ClusterMSA.py

Line 115-116
```
            if eps>10 and n_clust==1:
                break
```

thank you very much!
Tengyu

**Comment by HWaymentSteele** [comment]
Hi Tengyu, thanks for your interest in the code! I coded it as such because I was finding in my screening that eps was typically smaller than 10 and if by 10 the number of clusters detected was only 1, then it was a waste of time to continue scanning larger values.

Can I ask roughly your MSA sizes and protein lengths are to be encountering this? I am happy to move it to be an optional flag, or if you’d like to submit a PR, happy to go that route too.

Best,

Hannah

**Comment by miss77jun** [comment]
Thanks for your reply. 

I got your meaning. But the condition is a little tough for some MSAs. Note I generated MSAs following the protocol of AF2. Moving the condition to an optional flag is a good way to make the program more flexible. 

One case is 3QF4_A, whose MSA size is 8359 and sequence length is 572. 

Regards
Tengyu

**Comment by chenyuwai** [comment]
Hello, I support to add more code to make the system more general. In my case, epsilon ~ 22. I got this after I edited the code to relax the maximum to be 30 and commented out the two break lines mentioned by the original poster. However, I am struck with an error downstream and wonder if you could help me to get over it. Part of the output is listed below:

```
Selected eps=22.00
4717 total seqs
189 clusters, 891 of 4717 not clustered (0.19)
avg identity to query of unclustered: 0.32
avg identity to query of clustered: 0.40
Traceback (most recent call last):
  File "/content/AFcluster/scripts/ClusterMSA.py", line 152, in <module>
    cs = consensusVoting(tmp.sequence.tolist())
  File "/content/AFcluster/scripts/utils.py", line 59, in consensusVoting
    baseArray = [x[i] for x in seqs]
  File "/content/AFcluster/scripts/utils.py", line 59, in <listcomp>
    baseArray = [x[i] for x in seqs]
IndexError: string index out of range
---------------------------------------------------------------------------

```
I prepared my MSA with a locally installed colabfold with default parameters. The query sequence is about 500 residues long. Please advise.
