### ISSUE TITLE
--min_eps and --eps_step flags not recognized

### ISSUE THREAD

**Issue by mariagviegas** [HWaymentSteele/AF_Cluster#9]
Hello,
because the program does not find any clusters for my protein sequence with the standard clustering settings, I was trying to change some of the epsilon settings. The "--eps_val" flag seems to be working. But once I try with "--min_eps" or "--eps_step", I get the following errors:

python scripts/ClusterMSA.py EX -i /home/pbuser/Documents/Maria/230809_test_af_cluster_SacETF/2ndtry/input/SacETF_cdc32.a3m -o /home/pbuser/Documents/Maria/230809_test_af_cluster_SacETF/2ndtry/output/standard --min_eps 1
EX
20240 seqs removed for containing more than 25% gaps, 646 remaining
Traceback (most recent call last):
  File "/home/pbuser/af_cluster/AF_Cluster/scripts/ClusterMSA.py", line 101, in <module>
    eps_test_vals=np.arange(args.min_eps, args.max_eps+args.eps_step, args.eps_step)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

AND

python scripts/ClusterMSA.py EX -i /home/pbuser/Documents/Maria/230809_test_af_cluster_SacETF/2ndtry/input/SacETF_cdc32.a3m -o /home/pbuser/Documents/Maria/230809_test_af_cluster_SacETF/2ndtry/output/standard --eps_step .5
EX
20240 seqs removed for containing more than 25% gaps, 646 remaining
Traceback (most recent call last):
  File "/home/pbuser/af_cluster/AF_Cluster/scripts/ClusterMSA.py", line 101, in <module>
    eps_test_vals=np.arange(args.min_eps, args.max_eps+args.eps_step, args.eps_step)
                                          ~~~~~~~~~~~~^~~~~~~~~~~~~~


It kind of seems like the input values were not being converted into floats and taken as strings.
Thank you in advance for your help!
Best,
María

**Comment by chenyuwai** [comment]
I also got this error. This can be solved by adding "type=" into the following 4 option definitions in ClusterMSA.py

`    p.add_argument('--min_eps', action='store',default=3, type=float, help='Min epsilon value to scan for DBSCAN (Default 3).')
    p.add_argument('--max_eps', action='store',default=20, type=float, help='Max epsilon value to scan for DBSCAN (Default 20).')
    p.add_argument('--eps_step', action='store',default=.5, type=float, help='step for epsilon scan for DBSCAN (Default 0.5).')
    p.add_argument('--min_samples', action='store',default=3, type=int, help='Default min_samples for DBSCAN (Default 3, recommended no lower than that).')
`
